name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🔥 instalar deps do backend
      - name: Install backend deps
        run: |
          cd backend
          npm ci

      # 🔥 subir API
      - name: Start backend
        run: |
          cd backend
          npm run start &

      # ⏳ esperar API subir
      - name: Wait for API
        run: npx wait-on http://localhost:5000

      # 📦 instalar deps do cypress (raiz)
      - name: Install frontend deps
        run: npm ci

      # 🧪 rodar testes
      - name: Run Cypress
        run: npm test