name: Sauce demo and React Gram API tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Start app
        run: npm run start &

      - name: Wait app
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: npx cypress run
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
